const STRINGS = {
    "nimiq_safe_title": "Nimiq Safe",
    "nimiq_safe_name": "NIMIQ SAFE<sup>BETA</sup>",
    "safe_locked": "Your Nimiq Safe is locked",
    "draw_pattern": "Draw your pattern to unlock:",
    "using_testnet": "You are connecting to the Nimiq Testnet. Please <strong>do not</strong> use your Mainnet accounts in the Testnet!",
    "private_browsing": "You are using Private Browsing Mode. Your accounts will not be saved when this window is closed. Please make sure to <strong>create a backup / upgrade</strong>!",
    "disclaimer_title": "Disclaimer",
    "not_web_wallet": "Always backup your recovery words, passphrase, pin and keys. Please note that safe.nimiq.com, keyguard.nimiq.com & miner.nimiq.com are not \"web wallets\". <strong>You do not create an account or give us your funds to hold onto.</strong> You hold your keys. We only make it easy for you, through a browser, to create, save, and access your information and interact with the blockchain.",
    "safe_is_beta": "We are not responsible for any loss. Nimiq, safe.nimiq.com, keyguard.nimiq.com & miner.nimiq.com, and some of the underlying libraries are under active development. While we thoroughly test, there is always the possibility something unexpected happens that causes your funds to be lost. Please do not place more than you are willing to lose, and please be careful.",
    "close_modal": "close",
    "dashboard": "Dashboard",
    "history": "History",
    "settings": "Settings",
    "send": "Send",
    "receive": "Receive",
    "contacts": "Contacts",
    "recent_transactions": "Recent Transactions",
    "your_accounts": "Your Accounts",
    "nimiq_network": "Nimiq Network",
    "transaction_history": "Transaction history",
    "show_info_slides": "Show information slides",
    "create_done": "Account created successfully.",
    "create_fail": "Account was not created.",
    "upgrade_done": "Account upgraded successfully.",
    "upgrade_fail": "Upgrade not completed.",
    "backup_done": "Account backed up successfully.",
    "backup_fail": "No backup created.",
    "rename_done": "Account renamed successfully.",
    "rename_fail": "Account was not renamed.",
    "import_done": "Account imported successfully.",
    "import_fail": "Account was not imported.",
    "import_no_ledger_support": "Your browser does not have Ledger support or it is not enabled.",
    "unconfirmed_ledger": "Ledger Account not confirmed.",
    "offline_start_height_needed": "In offline mode, the validity-start-height needs to be set (advanced settings).",
    "no_consensus": "Consensus not yet established, please try again in a few seconds.",
    "tx_send_fail": "Transaction could not be sent",
    "tx_send_done": "Transaction sent!",
    "visual_lock_set": "Visual lock set!",
    "upgrade_title": "Please Upgrade your Account",
    "upgrade_reason": "To protect your funds, please upgrade your account to a Nimiq Safe Account. You will create a backup and get a nice green checkmark.",
    "upgrade_button": "Upgrade now",
    "safe_description": "The Nimiq Safe app to manage your NIM",
    "show_all_decimals": "Show all decimals",
    "show_all_decimals_explain": "Show all five decimals when displaying balances.",
    "visual_lock": "Visual lock",
    "visual_lock_explain": "Lock access to the Safe with a pattern whenever the website is visited.",
    "send_prepared_tx": "Send prepared transaction",
    "send_prepared_tx_explain": "Send a transaction that was prepared offline.",
    "delete_cache": "Delete cached data",
    "delete_cache_explain": "This does not delete your accounts. It only deletes your transaction history and balances, which will be loaded again from the network.",
    "remove_lock_verify": "Do you want to remove the lock?",
    "visual_lock_setup_title": "Set up visual lock",
    "visual_lock_setup_prompt": "Draw a pattern to visually lock the Safe:",
    "total_balance": "Total balance",
    "intro_title": "Welcome to Nimiq Safe",
    "intro_subtitle": "What is the Nimiq Safe?",
    "intro_list_1": "Nimiq Safe lets you securely manage your Nimiq accounts, send and receive NIM and view your balances.",
    "intro_list_2": "Nimiq Safe is a free and open-source, client-side interface.",
    "intro_list_3": "Nimiq Safe allows you to interact directly with the blockchain while remaining in full control of your keys & your funds.",
    "intro_create_account": "For using Nimiq Safe, you need an account:",
    "intro_create_account_button": "Create New Account",
    "intro_recover": "If you have 24 Recovery Words or an Access File, you can use those to import your existing account:",
    "intro_24_words": "Import from 24 Words",
    "intro_access_file": "Import from Access File",
    "intro_ledger": "Import Ledger Account",
    "intro_upgrade_account": "You can upgrade your existing Account for Nimiq Safe",
    "intro_upgrade_button": "Upgrade account",
    "intro_existing_account_import_instead": "Or if you have 24 Recovery Words or an Access File, you can use those to import your account.",
    "copyright_notice": "MIT License Copyright © 2018 Nimiq Foundation",
    "copyright_notice_short": "© 2017-2018 Nimiq Foundation",
    "ledger_confirmed": "Ledger account confirmed."
};
export function getString(id) {
    return STRINGS[id] ? STRINGS[id] : "(missing translation: " + id + ")";
}
